import { FC, ReactNode } from 'react'
import type { Metadata } from 'next'

import styles from '@/styles/Global.module.scss'

export const metadata: Metadata = {
  title: 'Nextjs Boilerplate',
  description: 'Generated by create next app'
}

interface RootLayoutProps {
  children: ReactNode
}

const RootLayout: FC<RootLayoutProps> = ({ children }) => (
  <html lang="en">
    <body className={styles.app}>{children}</body>
  </html>
)

export default RootLayout
