import { Home as HomeScreen } from "@/screens"
import type { Metadata } from 'next'

export const metadata: Metadata = {
	title: 'Nextjs Boilerplate',
	description: 'Generated by create next app'
}

const Home = () => <HomeScreen />

export default Home
